name = "vulgate"
uuid = "fa7963a8-32eb-4b5b-90b4-f183e41f328a"
authors = ["Sanity Sierota <47074795+that-hatter@users.noreply.github.com>"]
version = "0.1.0"

[deps]
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
